### PR TITLE
Fix ladder recipe; add ladder->stick recipe

### PR DESCRIPTION
**Pull request by ClobberXD**
### Proposed changes
- Ladder's craft recipe requires `default:stick 7` and not `default:wood 7`; fixed.
- Add recipe for obtaining 2 sticks from a ladder. i.e. Make ladder crafting reversible.

@rubenwardy, I'll also add recipes for `wooden tools -> sticks and wood` if that's ok with you...

### CODE REVIEW

**Comment by rubenwardy** [comment]
Sure

**Comment by ClobberXD** [comment]
Done. Since only one item can be the craft output, all wood tools will only yield `default:wood <1 to 3>`.

**Comment by ClobberXD** [comment]
Bump! :)

**Comment by ClobberXD** [comment]
Anything else that needs addressing?

**Pull request merged**
