### PR TITLE
Modifications to random_messages, shooter:grenade and more

### PR DESCRIPTION
**Pull request by ClobberXD**
## Proposed changes
- Added more advisories to random_messages.messages and reduced the interval between messages from 120 seconds to 60 seconds.
- Tweaked the blast damage and blast radius of grenade, for enhanced realism _(related to **#104**)_
- Fixed middle red barrier not emerging underwater _(related to **#91**)_
- Decreased stack_max of apples from 99 to 30.

Thanks in advance!

### CODE REVIEW

**Comment by afshaan4** [comment]
Thanks, those extra messages are great.

**Comment by ClobberXD** [comment]
Another commit to fix middle red barrier not emerging underwater.

@rubenwardy - can you merge this PR please - it's getting more and more commits added to it :P

**Comment by afshaan4** [comment]
That should fix #91

**Comment by ClobberXD** [comment]
Yes, both 2 Hills and 2 Lakes, and The Bridge. But the .schem file has to be re-created, with the modified barriers.

**Comment by rubenwardy** [comment]
The CTF barrier isn't quite the fix I wanted to do - I was planning on adding another barrier type which looks the same as the red glass, but is replaced with water_source rather than air when the barrier goes down.

/post and the team formspec isn't a feature which CTF is meant to have, I actually forgot to remove it.

**Comment by ClobberXD** [comment]
Do you mean replacing the barrier with water source when the 'ding' is sounded?

/post isn't meant to exist? O_O too bad... it's really useful to convey long-term information to team-members - e.g. When the pro-chest gets full, I stash away the rest of the loot in safe place, and /post the co-ordinates of the stash - this way, the info isn't lost in seconds (which is the case when using /t), and is conveniently saved to a formspec.

**Comment by rubenwardy** [comment]
merged

**Pull request closed without merging**
