### PR TITLE
Kick players that camp with the flag

### PR DESCRIPTION
**Pull request by MinetestSam**
Warning is given first, if the player camps with the flag
If done again, the player is kicked.

### CODE REVIEW

**Comment by ClobberXD** [comment]
Not sure if `ctf_flag.register_on_drop` is called _only_ when the `flag.drop_time` expires. @rubenwardy?

**Comment by rubenwardy** [comment]
This is a hack at best. A bad idea at worst

**Comment by ClobberXD** [comment]
Oh... :/
All `ctf*.register_on_*` callbacks need to be documented...

**Comment by ClobberXD** [comment]
These changes should be added to the existing [flag capture timeout code](https://github.com/rubenwardy/ctf_pvp_engine/blob/e2a59cef6eba80464af5414d89c4e1c6fbfd597c/ctf_flag/init.lua#L131)

**Pull request closed without merging**
